controllers:
    resource: ../../src/Controller/
    type: annotation

admin:
    resource: ../../src/Controller/Admin/
    prefix: '/admin'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
